### ISSUE TITLE
Chrome 71 remove URL.createObjectURL from MediaStream

### ISSUE THREAD

**Issue by b1ngx** [a-wing/webrtc-book-cn#1]
> 关于返回的流如何附加到 <video> 元素，请注意，Chrome 要求转换为所谓的 Blob URL（video.src = window.URL.createObjectURL(stream);），而其他启用 WebRTC 的浏览器允许您按原样使用它（video.src = stream;）。

Chrome 71 remove URL.createObjectURL from MediaStream

https://developers.google.com/web/updates/2018/10/chrome-71-deps-rems#remove_urlcreateobjecturl_from_mediastream

The sample code does not work in modern browsers and needs to be modified

```
video.src = window.URL.createObjectURL(stream);
```

to:

```
video.srcObject = stream;
```

**Comment by a-wing** [comment]
Thank you very much, the original book content is relatively old, some demos I have not fully tested
